### ISSUE TITLE
Galacticraft Asteroids base texture change

### ISSUE THREAD

**Issue by radfast** [Zerrens/InterstellarOres#3]
Nice job, I have only recently become aware of your mod.  It's well done, looks great.  We added a link to it on the Galacticraft wiki here:
http://wiki.micdoodle8.com/wiki/Config#Adding_ores_from_other_mods
(if you prefer us to give a link to a different mod homepage or download link, just let me know, or edit the page yourself)

Please be aware of Asteroid base rock texture change in Galacticraft 3.0.9:
https://github.com/micdoodle8/Galacticraft/commit/7d1cb5c16c82d1ff18fedebc68f88bd5c3bcddf8

I think we will stick to this now, I do not think there will be any more changes in Asteroids.

**Comment by ChatFawkes** [comment]
Thanks for adding the link to the wiki. I updated Galacticraft in my packs a few days ago and noticed the texture change, so let me fix this now.
